### create a group

POST http://localhost:3000/groups HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibmlja25hbWUiOiJyYWJiaXQiLCJpYXQiOjE1NTQwMTY3ODQsImV4cCI6MTU1NDYyMTU4NH0.F_QQHYceYmKudPtCLXpeSqNU43cuiDYLIAXDxsJPjEE
Content-Type: application/json

{
  "name": "a512"
}
