### get all users

GET http://localhost:3000/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJuaWNrbmFtZSI6InJhYmJpdCIsImlhdCI6MTU1MjgxOTIzMCwiZXhwIjoxNTUyODIyODMwfQ.7SlNPe4qJdxde2qCUaju7VZOfEER2AOpxBQ8q2pBprY

### get one user by id

GET http://localhost:3000/users/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJuaWNrbmFtZSI6InJhYmJpdC1hNTEyIiwiaWF0IjoxNTUyNzQ0NjczLCJleHAiOjE1NTI3NDgyNzN9.WUrHgIbgfxn-pqdLZtpp2N9hc2KU9bZtFA7_1f6-Yc8

### create a new user

POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
  "username": "admin_syf",
  "nickname": "rabbit-a512",
  "password": "123123"
}

### update a user by id

PUT http://localhost:3000/users/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJuaWNrbmFtZSI6InJhYmJpdC1hNTEyIiwiaWF0IjoxNTUyNzQ2NDYwLCJleHAiOjE1NTI3NTAwNjB9.yD4pCowzzAgkN-_04RZRnkoqjsRJNxf-R_VuhqTEQlU
Content-Type: application/json

{
  "nickname": "rabbit",
  "password": "123"
}

### delete a user by id

DELETE http://localhost:3000/users/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJuaWNrbmFtZSI6InJhYmJpdC1hNTEyIiwiaWF0IjoxNTUyNzQ0NjczLCJleHAiOjE1NTI3NDgyNzN9.WUrHgIbgfxn-pqdLZtpp2N9hc2KU9bZtFA7_1f6-Yc8

### change password

POST http://localhost:3000/users/change-password HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJuaWNrbmFtZSI6InJhYmJpdCIsImlhdCI6MTU1MjgyMzgzNSwiZXhwIjoxNTUyODI3NDM1fQ.AJ23dfp5Dl_l39FjZt0IwlONj6E2A-dGIdUAYfsXkXY
Content-Type: application/json

{
  "old_password": "123123",
  "new_password": "123123"
}
